[package]
authors = ["Saksama Terminal <saksama@localhost.localdomain>"]
edition = "2018"
name = "wasm-worker-memory-test"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
wee_alloc = {version = "0.4.5", optional = true}
